[common]
platform = espressif32
framework = espidf
build_type = release
upload_speed = 921600
monitor_speed = 921600
monitor_echo = yes
monitor_filters = esp32_exception_decoder
extra_scripts =
    pre:bin/compdb_path.py
    pre:bin/select_port.py
    pre:bin/build_flags.py
build_unflags =
    -std=gnu17
    -std=gnu++2b
    -DBOARD_HAS_PIN_REMAP
upload_protocol = esptool
build_flags =
    -std=gnu++23
    -fdiagnostics-format=sarif-file

[esp32]
extends = common
build_flags =
    ${common.build_flags}
    -DPLATFORM_ESP32_ORIG
    -DPLATFORM_ESP32
    -DESP32_CMAKE

board = custom_nodemcu_esp32
board_build.partitions = partitions_esp32.csv

[esp32s3]
extends = common
build_flags =
    ${common.build_flags}
    -DPLATFORM_ESP32
    -DPLATFORM_ESP32S3
    -DESP32_CMAKE
    -DBOARD_HAS_PSRAM
    -DBOARD_USES_HW_GPIO_NUMBERS
    -mfix-esp32-psram-cache-issue

board = custom_nano_esp32
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_build.partitions = partitions_esp32s3.csv
board_upload.flash_size = 16MB

[esp32c3]
extends = common
board = custom_esp32c3_supermini
board_build.flash_mode = qio
board_upload.flash_size = 4MB
board_build.partitions = partitions_esp32c3.csv
build_flags =
    ${common.build_flags}
    -DPLATFORM_ESP32
    -DPLATFORM_ESP32C3
    -DESP32_CMAKE
    -DPIN_RESERVED_STRAP_RTC=GPIO_NUM_2
    -DPIN_RESERVED_STRAP_UART=GPIO_NUM_8
    -DPIN_RESERVED_BOOT=GPIO_NUM_9

[platformio]

[env:master]
extends = esp32
board_build.cmake_extra_args =
    -DSRC_ROOT:STRING="master"
custom_usb_serials =
    0001

[env:slave1]
extends = esp32c3
board_build.cmake_extra_args =
    -DSRC_ROOT:STRING="slave"

[env:slave2]
extends = esp32c3
board_build.cmake_extra_args =
    -DSRC_ROOT:STRING="slave

[env:listener]
extends = esp32s3
board_build.cmake_extra_args =
    -DSRC_ROOT:STRING="listener"
