[common]
# FIXME: 6.13 causes errors with Python 3.14
build_type = release
upload_speed = 921600
monitor_speed = 921600
monitor_echo = yes
extra_scripts =
    pre:bin/compdb_path.py
    pre:bin/sdkconfig.py
    pre:bin/select_port.py
    pre:bin/build_flags.py
    bin/reset_target.py
    post:bin/esp_size.py
build_unflags =
    -std=gnu17
    -std=gnu++2b
    -DBOARD_HAS_PIN_REMAP
upload_protocol = esptool
build_flags =
    -std=gnu++23
    -fdiagnostics-format=sarif-file

lib_deps =
    https://github.com/Neargye/magic_enum#v0.9.7
    https://github.com/d-bahr/CRCpp#release-1.2.1.0

[esp32]
extends = common

build_flags =
    ${common.build_flags}
    -DPLATFORM_ESP32
    -DESP32_CMAKE

board_build.cmake_extra_args =
    -DENABLE_SPI=OFF
    -DENABLE_I2C=OFF
    -DENABLE_I2S=OFF
    -DENABLE_PSRAM=OFF
    -DENABLE_LEDC=OFF
    -DENABLE_ADC=OFF
    -DENABLE_TEMP_SENSOR=OFF
    -DENABLE_TWAI=OFF
    -DENABLE_SDMMC=OFF
    -DENABLE_WIFI=OFF
    -DENABLE_BLUETOOTH=OFF
    -DENABLE_HTTPD=OFF

platform = espressif32@6.12
framework = espidf
monitor_filters = esp32_exception_decoder

[esp32orig]
extends = esp32
build_flags =
    ${esp32.build_flags}
    -DPLATFORM_ESP32_ORIG
board = custom_esp32_nodemcu
board_build.partitions = partitions/esp32_2mib.csv

[esp32s3]
extends = esp32

board_build.cmake_extra_args =
    ${esp32.board_build.cmake_extra_args}
    -DENABLE_PSRAM=ON

[esp32s3n16r8]
extends = esp32s3

[esp32s3fh4r2]
extends = esp32s3

[esp32c3]
extends = esp32

[esp32s3nano]
extends = esp32s3n16r8
board = custom_esp32s3_nano
board_build.partitions = partitions/esp32_16mib.csv

build_flags =
    ${esp32.build_flags}
    -DPLATFORM_ESP32S3
    -DPLATFORM_ESP32S3_NANO
    -DBOARD_HAS_PSRAM
# FIXME: Readd?
# -mfix-esp32-psram-cache-issue

[esp32s3zero]
extends = esp32s3fh4r2
board = custom_esp32s3_zero
board_build.partitions = partitions/esp32_4mib.csv

build_flags =
    ${esp32.build_flags}
    -DPLATFORM_ESP32S3
    -DPLATFORM_ESP32S3_ZERO
    -DBOARD_HAS_PSRAM
# FIXME: Readd?
# -mfix-esp32-psram-cache-issue

[esp32s3devkit]
extends = esp32s3n16r8
board = custom_esp32s3_devkit
board_build.partitions = partitions/esp32_16mib.csv

build_flags =
    ${esp32.build_flags}
    -DPLATFORM_ESP32S3
    -DPLATFORM_ESP32S3_DEVKIT
    -DBOARD_HAS_PSRAM

[esp32c3supermini]
extends = esp32c3
board = custom_esp32c3_supermini
board_build.partitions = partitions/esp32_4mib.csv

build_flags =
    ${esp32.build_flags}
    -DPLATFORM_ESP32C3
    -DPLATFORM_ESP32C3_SUPERMINI

[platformio]

[env:master]
extends = esp32s3devkit
build_flags =
    ${esp32s3devkit.build_flags}
    -DNODE_IDENTITY=Master
board_build.cmake_extra_args =
    ${esp32s3devkit.board_build.cmake_extra_args}
    -DSRC_ROOT:STRING="master"
    -DENABLE_SPI=ON
custom_usb_serials =
    123456

[env:media]
extends = esp32orig
build_flags =
    ${esp32orig.build_flags}
    -DNODE_IDENTITY=Media
board_build.cmake_extra_args =
    ${esp32orig.board_build.cmake_extra_args}
    -DSRC_ROOT:STRING="media"
    -DENABLE_SPI=ON
custom_usb_serials =
    0001

[env:gpu0]
extends = esp32s3zero
build_flags =
    ${esp32s3zero.build_flags}
    -DNODE_IDENTITY=GPUNode0
board_build.cmake_extra_args =
    ${esp32s3zero.board_build.cmake_extra_args}
    -DSRC_ROOT:STRING="gpu"
    -DENABLE_SPI=ON
custom_usb_serials =
    9C:13:9E:F1:3F:60
custom_sdkconfig = gpu

[env:gpu1]
extends = esp32s3zero
build_flags =
    ${esp32s3zero.build_flags}
    -DNODE_IDENTITY=GPUNode0
board_build.cmake_extra_args =
    ${esp32s3zero.board_build.cmake_extra_args}
    -DSRC_ROOT:STRING="gpu"
    -DENABLE_SPI=ON
custom_usb_serials =
    10:51:DB:5E:FA:1C
custom_sdkconfig = gpu

[env:io]
extends = esp32c3supermini
build_flags =
    ${esp32c3supermini.build_flags}
    -DNODE_IDENTITY=InputOutput
board_build.cmake_extra_args =
    -DSRC_ROOT:STRING="io"
