#pragma once

#include "sdkconfig.h"

#define HAVE_ASSERT
#define HAVE_EMBEDDED_TIME_MS
#define HAVE_FREERTOS_INCLUDE_PREFIX
#define HAVE_FREERTOS_TASK_NOTIFICATIONS

#define ENABLE_HCI_CONTROLLER_TO_HOST_FLOW_CONTROL
#define ENABLE_LOG_ERROR

#if CONFIG_IDF_TARGET_ESP32
#define ENABLE_CLASSIC
#endif

#ifdef ENABLE_CLASSIC
#define HCI_ACL_PAYLOAD_SIZE 1024
#define HCI_HOST_ACL_PACKET_LEN HCI_ACL_PAYLOAD_SIZE
#define HCI_HOST_ACL_PACKET_NUM 8
#define HCI_HOST_SCO_PACKET_LEN 0
#define HCI_HOST_SCO_PACKET_NUM 0

#define MAX_NR_HCI_CONNECTIONS 1
#define MAX_NR_L2CAP_SERVICES 4
#define MAX_NR_L2CAP_CHANNELS 4
#define MAX_NR_RFCOMM_MULTIPLEXERS 0
#define MAX_NR_RFCOMM_SERVICES 0
#define MAX_NR_RFCOMM_CHANNELS 0
#define MAX_NR_BTSTACK_LINK_KEY_DB_MEMORY_ENTRIES 0
#define MAX_NR_BNEP_SERVICES 0
#define MAX_NR_BNEP_CHANNELS 0
#define MAX_NR_GOEP_SERVER_SERVICES 0
#define MAX_NR_GOEP_SERVER_CONNECTIONS 0
#define MAX_NR_HFP_CONNECTIONS 0
#define MAX_NR_HID_HOST_CONNECTIONS 0
#define MAX_NR_SERVICE_RECORD_ITEMS 3
#define MAX_NR_AVDTP_STREAM_ENDPOINTS 1
#define MAX_NR_AVDTP_CONNECTIONS 1
#define MAX_NR_AVRCP_CONNECTIONS 0
#define MAX_NR_AVRCP_BROWSING_CONNECTIONS 0
#endif
