#!/usr/bin/env python3
"""Generate a host-side animation registry from animation headers.

The renderer must not keep a separate, hand-maintained animation dispatch table.
This script discovers animations by the local convention used by
include/LedDisplay/Animations: each animation lives in its own directory with
Animation.hpp for rendering and Config.hpp for the matching WIRE_MSG config.
"""

from __future__ import annotations

import argparse
import dataclasses
import pathlib
import re
from typing import Iterable


CONFIG_RE = re.compile(
    r"struct\s+WIRE_MSG\s+(?P<config>[A-Za-z_]\w*Config)\s*\{(?P<body>.*?)\n\};",
    re.S,
)
FIELD_RE = re.compile(
    r"^\s*(?P<type>(?:std::)?(?:u?int(?:8|16|32|64)_t)|bool)\s+"
    r"(?P<name>[A-Za-z_]\w*)\s*(?:=[^;]*)?;",
    re.M,
)
STRUCT_RE = re.compile(r"struct\s+(?P<name>[A-Za-z_]\w*)\s*\{(?P<body>.*?)\n\};", re.S)


@dataclasses.dataclass(frozen=True)
class Field:
    type_name: str
    name: str


@dataclasses.dataclass(frozen=True)
class Animation:
    name: str
    config: str
    header: str
    fields: tuple[Field, ...]


def animation_headers(root: pathlib.Path) -> Iterable[pathlib.Path]:
    directory = root / "include" / "LedDisplay" / "Animations"
    for path in sorted(directory.glob("*/Animation.hpp")):
        yield path


def discover_animation(path: pathlib.Path, root: pathlib.Path) -> Animation | None:
    text = path.read_text(encoding="utf-8")
    command_path = path.with_name("Config.hpp")
    command_text = (
        command_path.read_text(encoding="utf-8")
        if command_path.exists()
        else text
    )
    config_match = CONFIG_RE.search(command_text)
    if config_match is None:
        return None

    config_name = config_match.group("config")
    config_body = config_match.group("body")
    fields = tuple(
        Field(match.group("type"), match.group("name"))
        for match in FIELD_RE.finditer(config_body)
    )

    expected_name = config_name.removesuffix("Config")
    animation_name: str | None = None
    animation_body = ""
    for struct in STRUCT_RE.finditer(text):
        candidate = struct.group("name")
        body = struct.group("body")
        if candidate == expected_name and re.search(
            rf"\b{re.escape(config_name)}\s+config\s*\{{\}}\s*;", body
        ):
            animation_name = candidate
            animation_body = body
            break

    if animation_name is None:
        raise SystemExit(
            f"{path}: found {config_name}, but no matching animation struct"
        )

    return Animation(
        name=animation_name,
        config=config_name,
        header=str(path.relative_to(root / "include")),
        fields=fields,
    )


def cpp_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def read_expression(field: Field, config: str) -> str:
    target = f"config.{field.name}"
    if field.type_name == "bool":
        return f"readJsonBool(value, {target}, error, fieldName)"
    return f"readJsonInteger(value, {target}, error, fieldName)"


def emit_registry(animations: list[Animation]) -> str:
    includes = "\n".join(
        f'#include "{pathlib.PurePosixPath(animation.header)}"'
        for animation in animations
    )
    variant_types = ", ".join(
        f"Totem::LedDisplay::Animations::{animation.name}"
        for animation in animations
    )
    names = ", ".join(cpp_string(animation.name) for animation in animations)

    sections: list[str] = [
        "// Generated by tools/led-render/generate_registry.py. Do not edit.\n",
        "#pragma once\n\n",
        '#include "HostRuntime.hpp"\n',
        f"{includes}\n",
        "#include <array>\n",
        "#include <optional>\n",
        "#include <string>\n",
        "#include <string_view>\n",
        "#include <type_traits>\n",
        "#include <variant>\n\n",
        "namespace Totem::LedRender::Generated {\n\n",
        f"using Payload = std::variant<{variant_types}>;\n\n",
        f"inline constexpr std::array<std::string_view, {len(animations)}> "
        f"animationNames{{{names}}};\n\n",
    ]

    for animation in animations:
        config = f"Totem::LedDisplay::Animations::{animation.config}"
        sections.append(
            f"[[nodiscard]] inline bool apply{animation.name}Config("
            f"{config} &config, const JsonValue *configValue, "
            "std::string &error) {\n"
            "    if (configValue == nullptr) {\n"
            "        return true;\n"
            "    }\n"
            "    if (configValue->kind != JsonValue::Kind::Object) {\n"
            f"        error = \"Config for {animation.name} must be an object\";\n"
            "        return false;\n"
            "    }\n"
            "    for (const auto &[fieldName, value] : configValue->object) {\n"
        )
        if animation.fields:
            for index, field in enumerate(animation.fields):
                prefix = "if" if index == 0 else "else if"
                sections.append(
                    f"        {prefix} (fieldName == {cpp_string(field.name)}) {{\n"
                    f"            if (!{read_expression(field, config)}) {{\n"
                    "                return false;\n"
                    "            }\n"
                    "        }\n"
                )
            sections.append(
                "        else {\n"
                f"            error = \"Unknown config field for {animation.name}: \" + fieldName;\n"
                "            return false;\n"
                "        }\n"
            )
        else:
            sections.append(
                "        (void)value;\n"
                f"        error = \"Unknown config field for {animation.name}: \" + fieldName;\n"
                "        return false;\n"
            )
        sections.append("    }\n    return true;\n}\n\n")

    sections.append(
        "[[nodiscard]] inline std::optional<Payload> "
        "makePayload(std::string_view animation, const JsonValue *configValue, "
        "std::string &error) {\n"
    )
    for index, animation in enumerate(animations):
        prefix = "if" if index == 0 else "else if"
        namespace_name = f"Totem::LedDisplay::Animations::{animation.name}"
        config_name = f"Totem::LedDisplay::Animations::{animation.config}"
        sections.append(
            f"    {prefix} (animation == {cpp_string(animation.name)}) {{\n"
            f"        {config_name} config{{}};\n"
            f"        if (!apply{animation.name}Config(config, configValue, error)) {{\n"
            "            return std::nullopt;\n"
            "        }\n"
            f"        return Payload{{{namespace_name}{{.config = config}}}};\n"
            "    }\n"
        )
    sections.append(
        "    error = \"Unknown animation: \" + std::string(animation);\n"
        "    return std::nullopt;\n"
        "}\n\n"
    )

    sections.append(
        "[[nodiscard]] inline std::string_view name(const Payload &payload) {\n"
        "    return std::visit(\n"
        "        [](const auto &animation) -> std::string_view {\n"
        "            using Animation = std::remove_cvref_t<decltype(animation)>;\n"
    )
    for index, animation in enumerate(animations):
        prefix = "if constexpr" if index == 0 else "else if constexpr"
        namespace_name = f"Totem::LedDisplay::Animations::{animation.name}"
        sections.append(
            f"            {prefix} (std::is_same_v<Animation, {namespace_name}>) {{\n"
            f"                return {cpp_string(animation.name)};\n"
            "            }\n"
        )
    sections.append(
        "            else {\n"
        "                return \"Unknown\";\n"
        "            }\n"
        "        },\n"
        "        payload);\n"
        "}\n\n"
    )

    for function_name, return_type, expression in [
        (
            "defaultLayer",
            "Totem::LedDisplay::Layer",
            "Animation::defaultLayer",
        ),
        ("defaultLifetimeMs", "uint32_t", "Animation::defaultLifetimeMs"),
        (
            "style",
            "Totem::LedDisplay::AnimationStyle",
            "Animation::defaultStyle",
        ),
        ("requiresFullFrame", "bool", "Animation::requiresFullFrame"),
    ]:
        sections.append(
            f"[[nodiscard]] inline {return_type} {function_name}"
            "(const Payload &payload) {\n"
            "    return std::visit(\n"
            f"        [](const auto &animation) -> {return_type} {{\n"
            "            using Animation = std::remove_cvref_t<decltype(animation)>;\n"
            "            (void)animation;\n"
            f"            return {expression};\n"
            "        },\n"
            "        payload);\n"
            "}\n\n"
        )

    sections.append(
        "inline void render(const Payload &payload, "
        "Totem::LedDisplay::AnimationRenderContext &ctx) {\n"
        "    std::visit([&ctx](const auto &animation) { animation.render(ctx); }, payload);\n"
        "}\n\n"
        "} // namespace Totem::LedRender::Generated\n"
    )
    return "".join(sections)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=pathlib.Path, required=True)
    parser.add_argument("--out", type=pathlib.Path, required=True)
    args = parser.parse_args()

    root = args.root.resolve()
    animations = [
        animation
        for path in animation_headers(root)
        if (animation := discover_animation(path, root)) is not None
    ]
    if not animations:
        raise SystemExit("No animations discovered")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(emit_registry(animations), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
